### ISSUE TITLE
About c++ linking

### ISSUE THREAD

**Issue by GuoYS0010** [OSCPU/nexus-am#1]
用这套工具试图生成c++的可执行文件，但是再链接的时候报错了。请问是lib中的静态库不包含c++相关的内容吗

**Comment by GuoYS0010** [comment]
![image](https://github.com/OSCPU/nexus-am/assets/93571618/af491194-070a-4587-976c-7c54f1417eaf)

**Comment by GuoYS0010** [comment]
![Screenshot 2023-11-07 162145](https://github.com/OSCPU/nexus-am/assets/93571618/086b585e-e211-4b72-8814-ead290634c73)

**Comment by sashimi-yzh** [comment]
这是裸机开发环境, 不支持其他库.
